name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    environment: vps
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        HOST: 54.38.54.4
        USERNAME: ubuntu
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
        source: "."
        target: "~/backend"
    
    - name: Build the Docker image
      uses: appleboy/ssh-action@master
      with:
        host: 54.38.54.4
        USERNAME: ubuntu
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
        script: sudo docker build .
